import './globals.css'


export const metadata = {
  title: 'Next Auth Page',
  description: 'Generated by shiva',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  )
}
